version: "3.7"

services:
  admin-front-end:
    container_name: admin-front-end
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 4000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
